-- V463 - make every public @handle reachable at /app/u/{handle}.
--
-- Two shapes made a profile page 404 while the account was perfectly healthy,
-- both verified against production before writing this:
--
-- (a) A HANDLE CONTAINING A DOT is never routed to the locale-prefixed page.
--     /app/u/theo_p  answers 307 -> /en/app/u/theo_p and renders;
--     /app/u/theo_p. answers 200 with the not-found page, because a path
--     segment carrying a dot is taken for a static asset and skips the locale
--     rewrite. The handle is generated by slugifying the display name through
--     UsernameValidator.normalize, whose character class ([a-z0-9._-]) is right
--     for a USERNAME (it has to accept an email-shaped one) and wrong for a URL
--     SLUG. "theo p." became "theo_p.", and the page it named did not exist.
--     Five accounts were in this state.
--
-- (b) NO PROFILE ROW AT ALL. The handle is generated lazily, on the first read
--     of that user's public profile, so an account nobody has opened from
--     inside the app has no handle and cannot be addressed by one. Twenty-four
--     enabled accounts were in this state, including every seeded persona -
--     their profile pages could not be linked or shared at all.
--
-- The generator and the settings validator are fixed in UserService (dots are
-- now folded to '_' and refused on input); this migration repairs the rows that
-- already exist. Both statements are idempotent and safe to re-run.

-- --------------------------------------------------------------------------
-- (a) Fold dots out of existing handles, keeping uniqueness.
-- --------------------------------------------------------------------------
-- A collision is possible in principle (a.b and a_b both present), so the
-- candidate is suffixed until free. Nothing is renamed unless it actually
-- contains a dot, and a handle whose folded form is already taken by ANOTHER
-- user gets the suffix rather than failing the migration.
DO $$
DECLARE
    row_rec   RECORD;
    candidate TEXT;
    suffix    INT;
BEGIN
    FOR row_rec IN
        SELECT user_id, handle FROM auth.user_profiles WHERE handle LIKE '%.%'
    LOOP
        -- Fold dots, collapse the runs of '_' that folding can create, and trim
        -- the separators a trailing dot leaves behind ("theo p." -> "theo_p").
        candidate := trim(both '_' from regexp_replace(replace(row_rec.handle, '.', '_'), '_+', '_', 'g'));
        IF candidate IS NULL OR length(candidate) < 2 THEN
            candidate := 'user_' || row_rec.user_id;
        END IF;

        suffix := 1;
        WHILE EXISTS (
            SELECT 1 FROM auth.user_profiles
             WHERE handle = candidate AND user_id <> row_rec.user_id
        ) LOOP
            candidate := trim(both '_' from regexp_replace(replace(row_rec.handle, '.', '_'), '_+', '_', 'g'))
                         || '_' || suffix;
            suffix := suffix + 1;
        END LOOP;

        UPDATE auth.user_profiles SET handle = candidate, updated_at = NOW()
         WHERE user_id = row_rec.user_id;
    END LOOP;
END $$;

-- --------------------------------------------------------------------------
-- (b) Give every enabled account a profile row carrying a handle.
-- --------------------------------------------------------------------------
-- The slug source mirrors UserService.getPublicProfile: the chosen display name
-- when there is one, else the account username. Accents are folded by hand
-- rather than with unaccent(), which is an extension this database does not
-- carry; anything the fold cannot turn into a well-formed slug is skipped and
-- left to the lazy generator, which owns the general case.
--
-- profile_visibility is UNLISTED, matching UserProfileEntity's own default:
-- the page is readable by anyone holding the link but is not advertised to
-- search engines. This creates no page that was not already meant to exist -
-- it only makes it addressable.
DO $$
DECLARE
    row_rec   RECORD;
    base      TEXT;
    candidate TEXT;
    suffix    INT;
BEGIN
    FOR row_rec IN
        SELECT u.id,
               COALESCE(NULLIF(TRIM(o.display_name), ''), u.username) AS source
          FROM auth.users u
          LEFT JOIN auth.user_onboarding o ON o.user_id = u.id
          LEFT JOIN auth.user_profiles p   ON p.user_id = u.id
         WHERE u.enabled = TRUE
           AND p.user_id IS NULL
    LOOP
        base := lower(COALESCE(row_rec.source, ''));
        base := translate(base,
                          'àáâãäåçèéêëìíîïñòóôõöùúûüýÿ',
                          'aaaaaaceeeeiiiinooooouuuuyy');
        base := regexp_replace(base, '[^a-z0-9]+', '_', 'g');
        base := trim(both '_' from base);
        base := left(base, 32);
        base := trim(both '_' from base);

        -- Too short, or nothing survived the fold: leave it to the lazy path
        -- rather than minting a meaningless handle.
        CONTINUE WHEN base IS NULL OR length(base) < 2;

        candidate := base;
        suffix := 1;
        WHILE suffix < 100
              AND EXISTS (SELECT 1 FROM auth.user_profiles WHERE handle = candidate) LOOP
            candidate := left(base, 32 - (length(suffix::TEXT) + 1)) || '_' || suffix;
            suffix := suffix + 1;
        END LOOP;
        -- Still colliding after 100 tries: skip rather than insert a duplicate.
        CONTINUE WHEN EXISTS (SELECT 1 FROM auth.user_profiles WHERE handle = candidate);

        INSERT INTO auth.user_profiles (user_id, handle, profile_visibility, created_at, updated_at)
        VALUES (row_rec.id, candidate, 'UNLISTED', NOW(), NOW())
        ON CONFLICT (user_id) DO NOTHING;
    END LOOP;
END $$;
